name = "PipesCorrectedness"
version = "0.1.0"
keywords = ["pipes", "verification"]
defaultTargets = ["PipesCorrectedness"]
# moreLinkArgs = [
#   "-L./.lake/packages/LeanCopilot/.lake/build/lib",
#   "-lctranslate2",
# ]

[[lean_lib]]
name = "PipesCorrectedness"

# [[require]]
# name = "aesop"
# scope = "leanprover-community"
# git = "https://github.com/leanprover-community/aesop"

# [[require]]
# name = "Canonical"
# scope = "chasenorman"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Pipes"
path = "../pipes"

# [[require]]
# name = "batteries"
# scope = "leanprover-community"
# rev = "main"

# [[require]]
# name = "LeanCopilot"
# git = "https://github.com/lean-dojo/LeanCopilot.git"
# rev = "main"

# lake exe test-pipes

[[lean_exe]]
name = "test-pipes"
root = "PipesCorrectednessMain"
